document.write('<div class="clear"></div>')
document.write('<link rel="StyleSheet" href="http://resources.it168.com/it168_head_foot/include/footer.css?dt=2012" type="text/css" media="screen" />')
document.write('<div id="footer">')
document.write('	<p> <a rel="nofollow" href="http://www.it168.com/bottomfile/about.shtml">盛拓传媒简介</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/it168.shtml">关于IT168</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/hzhb.shtml">合作伙伴</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/ggfw.shtml">广告服务</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/sytk.shtml">使用条款</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/tgzn.shtml">投稿指南</a> | <a rel="nofollow" href="http://www.wintalent.cn:8031/wt5/sequelmedia/web/index">诚聘精英</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/lxwm.shtml">联系我们</a> | <a rel="nofollow" href="http://bbs.app111.com/">苹果论坛</a> | <a rel="nofollow" href="http://www.it168.com/bottomfile/sitemap/sitemap.html">网站导航</a> | <a rel="nofollow" href="http://archive.it168.com/">往日回顾</a> </p>')
document.write('	<address>')
document.write('	北京皓辰网域网络信息技术有限公司. 版权所有 <a rel="nofollow" href="http://www.it168.com/images/icp.jpg">京ICP证:060528号</a> 北京市公安局海淀分局网监中心备案编号：1101082001<br>')
document.write('	<a rel="nofollow" href="http://www.it168.com/1201/images/it168tv.pdf">广播电视节目制作经营许可证(京) 字第1234号</a> <a rel="nofollow" href="http://www.it168.com/huiyuan/it168.html">中国互联网协会会员</a> <a rel="nofollow" href="http://www.it168.com/icoimages/yczz.jpg">测绘资质证书（乙测资字11005067）</a> <a rel="nofollow" href="http://www.it168.com/1201/images/wlwh.pdf">网络文化经营许可证</a>')
document.write('	</address>')
document.write('	<div class="pic_div">')
document.write('	<a rel="nofollow" href="http://www.bj.cyberpolice.cn/index.jsp" class="pic1">网络110 报警服务</a> <a rel="nofollow" href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202008062400006" class="pic2">国家备案</a> <a rel="nofollow" href="http://ulic.baidu.com/client/clientDetailCerInfo.do?id=1602" class="pic3">百度联盟-认证</a> <a rel="nofollow" href="https://search.szfw.org/cert/l/CX20111226001272001316" class="pic4"></a>')
document.write('			</div>')
document.write('		</div>')
document.write('	</div>')