//2015-3-16 12:09:00
  function oo(v){return document.getElementById(v);} function sow(v){oo(v).style.display = "";} var wimurl='http://168.it168.com/newImage/';function Apfx(ou){return ou.indexOf('http://')==0?ou:wimurl+ou;} function shl(tag,ahtml){oo(tag).innerHTML=ahtml;} function gugaOnClick(gugaid, url,adtype, recHit, newWin){if(newWin) window.open(url); };
 function _cnzulr(adTag){return "http://168.it168.com/newImage/20140610/cnzzurl.html?adtage="+adTag+"&pageId=96&subcategoryId="} 
function daima74(oj,adtage)  {var b=oj.cCode.replace(new RegExp('&nbsp;','gm'),' ').replace(new RegExp('<h>d</h>','gm'),'d').replace(new RegExp('<h>t</h>','gm'),'t').replace(new RegExp('<h>D</h>','gm'),'D').replace(new RegExp('<h>T</h>','gm'),'T').replace(new RegExp('&lt','gm'),'<').replace(new RegExp('&gt','gm'),'>').replace(new RegExp('<h>\"</h>','gm'),"'").replace(new RegExp('&nbsp;','gm')," ").replace(new RegExp('<br>','gm'),"  ").replace(new RegExp('<h>--</h>','gm'),"--"); eval(b); }
function LG(adTag){ switch (adTag){
case 'ADV_1276':daima74({"cCode":"document.write(&lth&gt\"&lt/h&gt&ltscript&nbsp;type=\"text/javascript\"&nbsp;src=\"http://www.adhufeng.com/ads/adexchange/ad.html?siteId=4811\"&gt&lt/scr&lth&gt\"&lt/h&gt+&lth&gt\"&lt/h&gtipt&gt&lth&gt\"&lt/h&gt);sow(adtage);"},'ADV_1276');
break;
case 'ADV_1907':daima74({"cCode":"if(self&nbsp;==&nbsp;top){<br>document.write(\"&ltscript&nbsp;type=&lth&gt\"&lt/h&gttext/javascript&lth&gt\"&lt/h&gt&gtvar&nbsp;googletag&nbsp;=&nbsp;googletag&nbsp;||&nbsp;{};googletag.cmd&nbsp;=&nbsp;googletag.cmd&nbsp;||&nbsp;[];(function()&nbsp;{var&nbsp;gads&nbsp;=&nbsp;document.createElement(&lth&gt\"&lt/h&gtscript&lth&gt\"&lt/h&gt);gads.async&nbsp;=&nbsp;true;gads.type&nbsp;=&nbsp;&lth&gt\"&lt/h&gttext/javascript&lth&gt\"&lt/h&gt;var&nbsp;useSSL&nbsp;=&nbsp;&lth&gt\"&lt/h&gthttps:&lth&gt\"&lt/h&gt&nbsp;==&nbsp;document.location.protocol;gads.src&nbsp;=&nbsp;(useSSL&nbsp;?&nbsp;&lth&gt\"&lt/h&gthttps:&lth&gt\"&lt/h&gt&nbsp;:&nbsp;&lth&gt\"&lt/h&gthttp:&lth&gt\"&lt/h&gt)&nbsp;+&nbsp;&lth&gt\"&lt/h&gt//www.googletagservices.com/tag/js/gpt.js&lth&gt\"&lt/h&gt;var&nbsp;node&nbsp;=&nbsp;document.getElementsByTagName(&lth&gt\"&lt/h&gtscript&lth&gt\"&lt/h&gt)[0];node.parentNode.insertBefore(gads,&nbsp;node);})();&lt/scr\"+\"ipt&gt\");<br>document.write(\"&ltscript&nbsp;type=&lth&gt\"&lt/h&gttext/javascript&lth&gt\"&lt/h&gt&gtgoogletag.cmd.push(function()&nbsp;{googletag.defineSlot(&lth&gt\"&lt/h&gt/8456/IDG.CN_B2C_it168.com&lth&gt\"&lt/h&gt,&nbsp;[300,&nbsp;250],&nbsp;&lth&gt\"&lt/h&gtdiv-gpt-ad-1423811516750-0&lth&gt\"&lt/h&gt).addService(googletag.pubads());googletag.pubads().enableSingleRequest()googletag.pubads().collapseEmptyDivs();googletag.enableServices();});&lt/sc\"+\"ript&gt\");<br>document.write(\"&ltdiv&nbsp;id=&lth&gt\"&lt/h&gtdiv-gpt-ad-1423811516750-0&lth&gt\"&lt/h&gt&gt&lt/div&gt\");<br>document.write(\"&ltscript&nbsp;type=&lth&gt\"&lt/h&gttext/javascript&lth&gt\"&lt/h&gt&gtgoogletag.cmd.push(function()&nbsp;{&nbsp;googletag.display(&lth&gt\"&lt/h&gtdiv-gpt-ad-1423811516750-0&lth&gt\"&lt/h&gt);&nbsp;});&lt/scri\"+\"pt&gt\");<br>sow(adtage);}"},'ADV_1907');
break;
} if(oo(adTag)) oo(adTag).onclick=function(){oo('_cnzid').src=_cnzulr(adTag);} }
